# Generated by Django 4.2 on 2025-06-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('date', models.DateField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('presentation_design', 'Presentation Design'), ('graphics', 'Graphics & Print Design'), ('other_services', 'Other Services')], max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_price', models.CharField(blank=True, max_length=50, null=True)),
                ('style_name', models.CharField(blank=True, max_length=100, null=True)),
                ('style_file', models.FileField(blank=True, null=True, upload_to='style_files/')),
                ('delivery_date', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_slides', models.IntegerField(default=1)),
                ('delivery_option', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_option_price', models.FloatField(default=0)),
                ('estimated_price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('google_checkbox', models.BooleanField(default=False)),
                ('google_link', models.TextField(blank=True, null=True)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='team/images/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('group', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('COO', 'COO'), ('CTO', 'CTO'), ('DESIGNER', 'Designer'), ('PRESENTATION_EXPERT', 'Presentation Expert'), ('MEMBER', 'Team Member'), ('OTHER', 'Other')], default='MEMBER', max_length=50)),
                ('priority', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='testimonials/profile_images/pro.png', upload_to='testimonials/profile_images/')),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=400)),
                ('trustpilot_url', models.URLField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('brandingTemplates', 'Branding Templates'), ('brochure', 'Brochure'), ('businessPresentation', 'Business Presentation'), ('companyProfile', 'Company Profile'), ('flyer', 'Flyer'), ('graphicDesign', 'Graphic Design'), ('pitchDeckDesign', 'Pitch Deck Design'), ('dataVisualization', 'Data Visualization'), ('salesDesign', 'Sales Design'), ('trainingDeck', 'Training Deck'), ('toolKit', 'Toolkit'), ('launchPlan', 'Launch Plan'), ('proposalDeck', 'Proposal Deck'), ('proficiencyDeck', 'Proficiency Deck'), ('growthProposal', 'Growth Proposal'), ('investorDeck', 'Investor Deck'), ('technicalDeck', 'Technical Deck'), ('rebranding', 'Rebranding'), ('corporate', 'Corporate'), ('strategyDeck', 'Strategy Deck')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
